#[derive(Debug, PartialEq)]
pub(crate) enum Msg {
    Reload,
    NextItem,
    PrevItem,
    FirstItem,
    LastItem,
    NextPage,
    PrevPage,
    FirstPage,
    LastPage,
    OpenDetail,
    BackToList,
    ToggleHelpLocale,
    EnterCommand,
    AppendCommand(char),
    PopCommand,
    CancelCommand,
    ExecuteCommand,
    OpenGoto,
    NextGoto,
    PrevGoto,
    CancelGoto,
    ConfirmGoto,
    ScrollDetailDown,
    ScrollDetailUp,
}
